site_name: Scrapflow Documentation
nav:
  - Home: index.md
  - API Endpoints:
      - Data Gouv: api/data-gouv.md
      - DBpedia: api/dbpedia.md
      - Kaggle: api/kaggle.md
      - Aggregation: api/aggregate.md
  - Setup: setup.md
  - Tests: tests.md
theme:
  name: material
